# Generated by Django 3.2.10 on 2021-12-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0002_rename_testmodel_animemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=255)),
                ('name_jp', models.CharField(max_length=255)),
                ('tv_episodes', models.IntegerField(default=0)),
                ('movies', models.IntegerField(default=0)),
                ('episode_length', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('douban_ratings', models.FloatField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OldAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.FloatField(default=0)),
                ('illustration', models.FloatField(default=0)),
                ('music', models.FloatField(default=0)),
                ('passion', models.FloatField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('times_watched', models.IntegerField(default=0)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_zh', models.TextField()),
                ('month', models.CharField(max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonAnimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('broadcast_day', models.CharField(max_length=255)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('ranking', models.IntegerField(default=0)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime')),
            ],
        ),
        migrations.DeleteModel(
            name='AnimeModel',
        ),
    ]
