# Generated by Django 3.2.10 on 2021-12-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0003_auto_20211228_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldanime',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='seasonanimes',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='seasonranking',
            name='anime_id',
        ),
    ]
