# Generated by Django 3.2.10 on 2021-12-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0004_auto_20211228_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldanime',
            name='anime_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='anime_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonanimes',
            name='anime_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonranking',
            name='anime_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime'),
            preserve_default=False,
        ),
    ]
