# Generated by Django 3.2.10 on 2021-12-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0006_auto_20211228_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='douban_ratings',
            new_name='douban_rating',
        ),
    ]
