# Generated by Django 3.2.10 on 2021-12-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0007_rename_douban_ratings_anime_douban_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
