# Generated by Django 3.2.10 on 2021-12-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0008_alter_anime_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.FloatField(default=0)),
                ('illustration', models.FloatField(default=0)),
                ('music', models.FloatField(default=0)),
                ('passion', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='times_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='OldAnime',
        ),
        migrations.AddField(
            model_name='animerating',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangumi_ratings_backend.anime'),
        ),
    ]
