# Generated by Django 3.2.10 on 2021-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0009_auto_20211228_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='douban_rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_length',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name_jp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='tv_episodes',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='seasonanimes',
            name='broadcast_day',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seasonanimes',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
