# Generated by Django 3.2.10 on 2021-12-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0010_auto_20211228_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
