# Generated by Django 3.2.10 on 2021-12-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0014_auto_20211228_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name_jp',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
