# Generated by Django 3.2.10 on 2021-12-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0016_auto_20211228_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonanimes',
            name='broadcast_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seasonanimes',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
