# Generated by Django 3.2.10 on 2021-12-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0017_auto_20211228_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonranking',
            name='date',
            field=models.DateField(),
        ),
    ]
