# Generated by Django 3.2.10 on 2021-12-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0018_alter_seasonranking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='illustration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='music',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='passion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='story',
            field=models.FloatField(default=0),
        ),
    ]
