# Generated by Django 3.2.10 on 2021-12-31 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0019_auto_20211230_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonAnimes',
            new_name='SeasonAnime',
        ),
        migrations.DeleteModel(
            name='AnimeRating',
        ),
    ]
