# Generated by Django 3.2.10 on 2022-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0020_auto_20211230_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='douban_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
