# Generated by Django 3.2.10 on 2022-04-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0021_anime_douban_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
