# Generated by Django 3.2.10 on 2022-04-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0022_delete_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='broadcast_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(default='', max_length=255),
        ),
    ]
