# Generated by Django 3.2.10 on 2022-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0023_auto_20220423_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='bangumi_tv_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='bangumi_tv_rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='delayed_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='dmhy_search_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='anime',
            name='dmhy_tags',
            field=models.TextField(blank=True, default='Lilith-Raws,NC-Raws,ANi'),
        ),
    ]
