# Generated by Django 3.2.10 on 2022-04-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0024_auto_20220423_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='cover_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
