# Generated by Django 3.2.10 on 2022-05-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0026_delete_seasonanime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='douban_link',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='douban_rating',
        ),
    ]
