# Generated by Django 3.2.10 on 2022-05-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangumi_ratings_backend', '0027_auto_20220508_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='movies',
        ),
    ]
